### ISSUE TITLE
ページ最下部の情報と、右上ボタンで出てくるメニューの情報が微妙に一致していない

### ISSUE THREAD

**Issue by kohonayoshi** [jaoafa/jaoweb4#135]
### 対象の機能

【現象詳細】
各ページ最下部の白背景の情報群と、各ページ右上の≡ボタンを押した際に出てくる黒背景の情報群が
一致していないことに違和感を覚えます
![image](https://github.com/jaoafa/jaoweb4/assets/52349485/07002cf8-d4d1-4fd5-bfc6-77ddb5c267ea)
![image](https://github.com/jaoafa/jaoweb4/assets/52349485/de8d8141-facd-4e06-96cb-50e54e1d11eb)

### 強化・改善の内容

・白背景の情報と黒背景の情報ができるだけイコールであるべきだと思います

以下は実装済であれば無視してもらって構いません
・白背景の情報と黒背景の情報が共通化されるべきだと思います
　(一方を変えるともう一方にも反映されるよう部品が共通化されている)

**Comment by Hiratake** [comment]
一致していると思うのですが、どこが一致していませんか？
メニューに出ている項目は、全てページ下部にも出ていると思います。

**Comment by kohonayoshi** [comment]
白背景の情報が黒背景に比べ、少ないように思えます。
統一したほうが「同じ情報が出てくることを利用者が容易に予想できる」という観点で良いと思います。

**Comment by book000** [comment]
一応、「項目」としては同じなんですけど説明文がフッターにはないんですよね。ここをどう考えるかかなあとは思います

**Comment by Hiratake** [comment]
長文になりますので、暇なときにでも…

ヘッダーのボタンを押した際に表示されるメニューは、普段は隠れていて、別のページへ移動するために閲覧者が「ボタンを押す」というアクションを押したときに表示されるものです。
この場合、閲覧者は「別のページへ移動したい」という意志があるはずなので、閲覧者にはページを移動するための手助けをする情報を与えるべきだと考えます。

一方、ページ最下部（フッター）は、ページを一番下までスクロールした場合に表示されるエリアです。
たまたま検索で出てきた記事を開き、最後まで読み終わったときにフッターが表示されるわけです。
このとき、閲覧者には「別のページへ移動したい」という気持ちが無いことのほうが多いのではないでしょうか？必要な情報は得られたしページを閉じよう、となるでしょう。

そんな閲覧者に対して、フッターに配置したナビゲーションは、「このサイトには他にこういうページがありますよ！」ということを伝え、閲覧者に他のページも見てもらう、回遊性を高める目的があります。
とくに別のページを見ようという気持ちのない閲覧者に対して、大量の文字列をぶつけてしまうと、わざわざそれを読もうとはならないのでは？と思います。
したがって、なるべく情報の量を減らしつつ、他にどのようなページがあるのかをざっくり把握できるくらいが良いと考えます。

また、サイトマップ的な役割もあります。サイト内にどのようなページがあるのか、全体像を把握できるようにするものです。
この目的のためには、なるべくひと目でページの一覧を確認できるほうが良いと考えます。
各項目の説明文を表示してしまうと、その分ひとつひとつの項目が使うエリアが広くなり、画面内に表示される項目数が減ります。（スマートフォンは画面が小さいので特に）


デザイン的にも、現在の状態に説明文を表示するのは微妙かなと思います。（これは私の個人的な感想になりますが）
フッターにナビゲーションを配置しているウェブサイトで、各項目の説明を入れているサイトは多くないと思います。

https://www.figma.com/ja/
https://dribbble.com/
https://evernote.com/intl/jp

項目名だけでなく説明文も表示して、それをうまく伝えられるようにデザインするのは、ちょっと私では経験・力量不足です。参考にできるサイトなどあれば良いのですが…

どうしても「同じ情報が出てくることを利用者が容易に予想できる」ようにしたほうが良い、ということであれば、納得できる理由をください。がんばってみます。

**Comment by kohonayoshi** [comment]
全面的に同意しますのでクローズします。お手数おかけしすみませんでした。

**Comment by Hiratake** [comment]
ご意見いただけることは大変ありがたいですので、他にも気になる箇所などあればご指摘ください。

あと、書けてなかったですが、

> ・白背景の情報と黒背景の情報が共通化されるべきだと思います
> (一方を変えるともう一方にも反映されるよう部品が共通化されている)

こちらについてはヘッダーもフッターも両方以下のデータを読んでいるので、内容がズレてしまうということはなさそうです。
https://github.com/jaoafa/jaoweb4/blob/main/src/app.config.ts#L16
