### ISSUE TITLE
devcontainer: `fatal: detected dubious ownership in repository` が発生する

### ISSUE THREAD

**Issue by book000** [jaoafa/jaoweb4#148]
codespace環境では発生しませんが、ローカルのdocker環境にて発生します

https://qiita.com/P-man_Brown/items/5628ef68f51d1acf38e0

**Comment by book000** [comment]
直そうとおもい1時間くらいからかいましたが直りませんでした。

`postCreateCommand` で `safe.directory` に追加しても変わらずエラー発生するし、変数でパス展開せずに `/workspaces/jaoweb4` を対象としてもダメだし、なんでなんでしょうか…
このエラーは `npm ci` 実行時に発生します

**Comment by book000** [comment]
どのラベルつけるのがいいんだ…？PR募集みたいなあれにしたいんだけど

**Comment by Hiratake** [comment]
devcontainer使わないからわがんね

**Comment by book000** [comment]
おま環っぽいのでクローズします、ごめんなさい！
