### ISSUE TITLE
PR 内で `@github-actions format` とリプライすると `npm run format` を実行するようにする

### ISSUE THREAD

**Issue by book000** [jaoafa/jaoweb4#151]
表題のとおり。

https://github.com/jaoafa/jaoweb4/pull/149#issuecomment-1597834456 を参照。
フォーク先に対しても触れるかどうかが微妙なので、別リポジトリで検証必須。

**Comment by book000** [comment]
いろいろ試しましたが、うまくいきませんでした。
https://github.com/book000/playground/blob/main/.github/workflows/comment-format.yml

少なくとも、非フォーク環境では期待通り動作します。
しかし、フォークからのPRの場合、`Maintainers are allowed to edit this pull request.` であってもローカルからPRブランチに対してコミットすることがどうにもできません（non-fast-forwardかpermission deniedが出ます）
ローカルでフォークプルリクに対してコミット出すことはできないんですかね…？Webオンリー？

**Comment by book000** [comment]
実用環境（実際に利用されてるワークフロー）ないですかねえ。ググってもフォーク先からPR出されることを想定してない記事ばっかりで、それだとupstreamにブランチ作ってプッシュされるよね？みたいな感じのやつばっかりです

**Comment by book000** [comment]
https://docs.github.com/ja/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork

できないが…？になってます

**Comment by book000** [comment]
ワークフローに落とし込むにしても、ローカルで再現できない限りGitHub Actionsでもできないんですけどねえ。うーむ

**Comment by Hiratake** [comment]
[Nuxt のワークフロー](https://github.com/nuxt/nuxt/blob/main/.github/workflows/autofix-docs.yml) 見てたら、 `docs/` 以下の変更が合った場合に、 [autofix.ci](https://github.com/apps/autofix-ci) っていう GitHub App 使って変更してる？ぽいんですけど、使えたりしませんか。

**Comment by book000** [comment]
ほーん…。コード見てもAPIサーバ側でどんな挙動してるのかわからんのが気になるところではあるけど、まあGitHub Appならシークレット関連も見えないはずだしまあ使ってみてもいいかもな…。playgroundでためしてみます

**Comment by Hiratake** [comment]
ESLint と Stylelint と Prettier はコミットしたら自動でなおすようにしました。 #166

**Comment by Hiratake** [comment]
https://github.com/reviewdog/reviewdog
