### ISSUE TITLE
textlint: `ウェブサイト` ではなく `Web サイト` で統一する

### ISSUE THREAD

**Issue by book000** [jaoafa/jaoweb4#152]
https://github.com/jaoafa/jaoweb4/pull/145#issuecomment-1602532049

**Comment by Hiratake** [comment]
https://github.com/jaoafa/jaoweb4/blob/main/src/content/4.support/2.faq.md?plain=1#L174
ここみたいに見出しに入っている場合は、間に半角スペースいらないみたいな設定になってる？

**Comment by book000** [comment]
ん、なんでだ？本文しか処理対象にならなかったりするのか？

**Comment by Hiratake** [comment]
意図的ではないのか
