### ISSUE TITLE
GitHub Pages でホスティングする

### ISSUE THREAD

**Issue by Hiratake** [jaoafa/jaoweb4#2]
### 内容

[jaoafa.com](https://jaoafa.com/) を GitHub Pages でホスティングして管理をラクにする。VPSに置かない。

**Comment by book000** [comment]
GitHub Actions から GitHub Pages にデプロイする方法ができたので、これを使うとよさそう。

[GitHub Pages: Custom GitHub Actions Workflows (beta)](https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta/)

DevelopersIO でこれをやっている[記事](https://dev.classmethod.jp/articles/github-pages-by-actions/)もあるし、book000/rss-deliver で GitHub Actions からの Pages アップロードを[している](https://github.com/book000/rss-deliver/blob/master/.github/workflows/update-rss.yml)のでできます。

**Comment by book000** [comment]
で、デプロイの処理を jaoweb4 と docs でやりたくないので、別リポジトリにその辺のデプロイ処理を投げようかと思う

というわけで、以降は https://github.com/jaoafa/jaoweb4-deploy

**Comment by book000** [comment]
暫定的にデプロイ処理については実装を終えているのでクローズします。本番環境（`jaoafa.com`）へのデプロイ先変更時に別の issue を開いてください。
