### ISSUE TITLE
jaoweb3からの継続要望

### ISSUE THREAD

**Issue by book000** [jaoafa/jaoweb4#24]
いったんひとつの issue に固めておきますが、複数 issue のほうがよければ言ってください。がんばります

- [ ] `authors.json` と `categories.json` を `content/blog` ではない別のディレクトリに移動する（jaoweb-docs 対応）
  https://github.com/jaoafa/jaoweb4/issues/25
- [ ] ブログ記事を検索 & カテゴリ別表示機能
  https://github.com/jaoafa/jaoweb4/issues/26
- [ ] 特定文字列を Markdown 内に書き込むと子ページの一覧が表示される機能
  https://github.com/jaoafa/jaoweb4/issues/27
- [ ] RSS Feed を生成する
  https://github.com/jaoafa/jaoweb4/issues/28
- [ ] 運営一覧の円形表示？
  https://github.com/jaoafa/jaoweb4/issues/29
- [ ] 他記事・ページへのリンクを張ると Embed カード（oEmbed）で表示される
  https://github.com/jaoafa/jaoweb4/issues/30
- [ ] 更新日時を自動表示
  https://github.com/jaoafa/jaoweb4/issues/31
- [ ] アラートコンポーネントの追加
  https://github.com/jaoafa/jaoweb/issues/212

**Comment by Hiratake** [comment]
特定文字列を Markdown 内に書き込むと子ページの一覧が表示される機能はたぶん対応できてるので認識ちがってたらおしえてください。

**Comment by Hiratake** [comment]
あとふつうに transfer issue みたいなのすればいいのでは

**Comment by book000** [comment]
Transfered

**Comment by Hiratake** [comment]
🙏
