### ISSUE TITLE
content/blogディレクトリにある2つのjsonファイルを他のディレクトリに配置するべきではないか

### ISSUE THREAD

**Issue by book000** [jaoafa/jaoweb4#25]
`content/blog` にある以下の2ファイルは `/static` などの別ディレクトリに配置し読み込むべきではないか？

これら二つのファイルは基本的に更新されることは少ないうえ、システム上 `content` 以下のファイルをすべて削除したうえで `jaoweb-docs` リポジトリをクローンするので、もし `content` ディレクトリに配置し続けるなら `jaoweb-docs` リポジトリで管理する必要がある。
とはいえ、 これらjsonファイルは `docs` ではない（関連するとはいえ）ので、別ディレクトリに配置するべきかと思う。`/static` でなくても可

**Comment by Hiratake** [comment]
とりあえずcontent内にjsonファイル置くのはやめたので一旦閉じます
