### ISSUE TITLE
特定文字列をMarkdown内に書き込むと子ページのリストが表示されるようにする

### ISSUE THREAD

**Issue by book000** [jaoafa/jaoweb4#27]
~~`<ChildrenList>`~~ -> `<PageList path="server">`

**Comment by book000** [comment]
`:content-list{:query='["docs"]'}` で docs 以下のページ一覧が生成されるらしい…？

**Comment by Hiratake** [comment]
content v2のMDC構文で、components/contentディレクトリ内のコンポーネントを.mdから呼び出せるのでそれでやってる感じ
https://content.nuxtjs.org/guide/writing/mdc/

**Comment by Hiratake** [comment]
tailwindのクラスもこういう感じで.mdから指定できるらしい…
https://tailwindcss.nuxtjs.org/examples/content/

一部だけ文字色変える時とかに使えそう？
（tailwindからデフォの色を消してるから使えない色ありそうだけど）

**Comment by book000** [comment]
`[]{}` 、違和感だ～…
