### ISSUE TITLE
トップページの運営一覧を円形状に配置

### ISSUE THREAD

**Issue by kohonayoshi** [jaoafa/jaoweb4#29]
特に意味はないですが、円形状にしてみたらスパイスが効いて良いかもしれません。
![image](https://user-images.githubusercontent.com/52349485/131088162-8ef44ef7-3349-4eef-88b9-8278d80617e4.png)

真ん中に原子核的にざくろを配置しても良いかもしれません(ゆうあ氏案)。
![image](https://user-images.githubusercontent.com/52349485/131088503-c289ab9c-394e-4f87-ae31-f7cb39fcc6e6.png)

**Comment by Hiratake** [comment]
サイト作り直しにあたってトップページも色々変える（そもそもトップページに運営メンバーの一覧いらんのでは？など）ので、せっかくアイデア出してもらったのに申し訳ないけど一旦無し。
