### ISSUE TITLE
他ページへのリンクを張るとカード/Embedでその記事を表示する

### ISSUE THREAD

**Issue by book000** [jaoafa/jaoweb4#30]
WordPressやZennとかでもある「他記事カードEmbed表示」が欲しいです。oEmbedとか呼ぶのかな？

他記事に誘導するときにリンクしかないと割と見落としがちなイメージがあるので…。

**Comment by Hiratake** [comment]
相当面倒そう。

https://blog.takumma.net/add-embed-link/
>  URL 先のメタデータを取得する API を用意する必要があります。

**Comment by book000** [comment]
ぐー。こんな厄介なのか…

**Comment by Hiratake** [comment]
https://nuxt.com/docs/guide/directory-structure/server
serverのとこでいい感じにコード書いたらgenerateしたときにいい感じになったりせんかなあ

**Comment by book000** [comment]
useAsyncDataでgenerate中に取得してレンダリングしてくれたらうれしいけどねえ。どうでしょ

**Comment by Hiratake** [comment]
なんもわからんのでPR出して♡

**Comment by Hiratake** [comment]
トップページつくるとか、先にやるべき内容あるので

**Comment by book000** [comment]
まあそれはそう

**Comment by Hiratake** [comment]
🙏

**Comment by book000** [comment]
とりあえずバックエンド部分に関してはなんとかなったけど、フロントのデザインがうまくいかない…、tailwindむず
![image](https://user-images.githubusercontent.com/8929706/224573710-f501c440-f6b3-40b8-a4ae-63e8a80d5362.png)
![image](https://user-images.githubusercontent.com/8929706/224573713-7711fbd5-be2d-48ba-9379-de29ac314b82.png)

**Comment by Hiratake** [comment]
つよそう
