### ISSUE TITLE
ページ遷移時、完全遷移後に表示されるページとは別のコンテンツが挟まる

### ISSUE THREAD

**Issue by book000** [jaoafa/jaoweb4#33]
- jaoafa/jaoweb4 c42ed4040f086320ac389ceb299b9bc4ddbf3237
- Node.js v18.13.0
- Firefox, Chrome 共に再現しました。
  - Mozilla Firefox 110.0.1
  - Google Chrome 110.0.5481.178

https://user-images.githubusercontent.com/8929706/223025922-6cb835bd-20ea-4d10-8532-1ec93e768d05.mp4

フッターメニューの項目をクリックしてページを遷移したとき、遷移後コンテンツとは異なるいくつかのコンテンツが表示されます。

1. ヘッダーとフッターを除く空白ページ
2. 遷移前コンテンツの横幅が広がったもの（はじめての方へページ）
3. 遷移後コンテンツの横幅が狭まったもの（ドキュメントページ）

ページ遷移時、ロード上の問題があるのだろうと推察しますが、リダイレクトしたかのように複数回異なるコンテンツが一瞬表示されるのは「あれ今のなんだ？」と不安感を与えそうです。
可能ならこの異なるコンテンツが表示されないような対応、または簡単なローディング画面などを挟むと違和感なく遷移できるかと思うのですが如何でしょうか。

上の動画でわかりにくければ、[こちらの GIF ファイル](https://user-images.githubusercontent.com/8929706/223026619-552ce84e-cb37-48de-9983-56f4aa329030.gif) をダウンロードして ScreenToGIF などで見るとわかりやすいかと思います。

よろしくお願いします。

**Comment by Hiratake** [comment]
これはdevですか？buildですか？
devだけであれば、問題ない認識です。

**Comment by book000** [comment]
`generate` で生成した成果物でも同様の問題が発生しているように見えます: https://jaoweb.amatama.net

**Comment by Hiratake** [comment]
このへんはnuxt contentが勝手にやってるからよくわからん。
layoutの変更がある場合に、ページの内容が更新される前にレイアウトだけ切り替わる→その後時間差でページの内容が切り替わる、っていう挙動に見えます。

nuxt3とかcontent v2の情報まだまだ少なくてよく分からんので、私の方でも調べますが、なんかあれば教えて欲しいです。
（document drivenモードなるものがcontent v2で追加されたので使ってみてます。）
