### ISSUE TITLE
記事内コンテンツのデザインについて

### ISSUE THREAD

**Issue by book000** [jaoafa/jaoweb4#34]
- jaoafa/jaoweb4 c42ed4040f086320ac389ceb299b9bc4ddbf3237
- Node.js v18.13.0
- Mozilla Firefox 110.0.1
- Google Chrome 110.0.5481.178

将来的にどのようなデザインにするのか把握していないのでアレなのですが、現状の様子を見るに、以下の点が気になります。
「ブログ記事サンプル (`/community/blog/example`)」を参考にしています。

いずれの検証およびスクリーンショットもローカルで `npm run dev` し、`localhost:3000` で閲覧していますが、`generate` の成果物である https://jaoweb.amatama.net でも再現を確認しています。

- 見出しの下線（リンク表記）
- インラインコードのデザイン
- #35
  - 見出し内部リンクがヘッダーに隠れる
  - 内部リンクでページを開いたとき、ヘッダーが透明になる

## 見出しの下線

![image](https://user-images.githubusercontent.com/8929706/223068120-0a3f34ea-75fe-4873-8812-92c62e53ad46.png)

すべての見出しに下線が入っているのが気になります。
内部リンクとして機能しているのはわかるのですが、下線までつけなくてもいいかなあ…という気がします。

## インラインコードのデザイン

![image](https://user-images.githubusercontent.com/8929706/223070472-7af9ad31-3b49-4af3-aafd-15078f0eb7e9.png)

意図的に `code::before` と `code::after` に \` を入れているようなのですが、Markdown から HTML への変換に失敗しているのか？と少し不安になります。
この記事を読む人にとっても、見出しをつけるときには文頭にグレイヴアクセントを含めていれなければならないのか？と多少誤認させてしまいそうです。
（特に、Minecraft コマンドを説明する際インラインコードにすることが多くあるので、そういう点でもミスを誘発しそうです）

<details>
<summary>#35 に分割されたため、折り畳んでいます</summary>

## 内部リンク部分がヘッダーに隠れる

![image](https://user-images.githubusercontent.com/8929706/223070012-d2608913-ba6d-467f-abf4-afde1a64d8ed.png)

`position: fixed` の影響で、内部リンクで飛んだ際、飛んだ先がヘッダーに隠れる問題があるようです。
ググると改善策はいくつかあるようですが、どれがデファクトスタンダードなのかよくわからないので、改善策はお任せします。

## 内部リンクでページを開いたとき、ヘッダーが透明になる

![image](https://user-images.githubusercontent.com/8929706/223072222-dee0e263-9307-4ced-892a-c1a38a9699e6.png)

ページを普通に開いたあと、コンテンツ内にある内部リンクをクリックした場合は問題ないのですが、他ページから内部リンク付きリンクを踏んで遷移した場合にヘッダーが透明になるようです。再現例は [こちら](https://jaoweb.amatama.net/community/blog/example/#%E8%A6%8B%E5%87%BA%E3%81%97)。
</details>

よろしくお願いいたします。

**Comment by Hiratake** [comment]
カスタマイズの方法メモ
https://tailwindcss.com/docs/typography-plugin#customizing-the-css

**Comment by Hiratake** [comment]
> 内部リンク部分がヘッダーに隠れる
> 内部リンクでページを開いたとき、ヘッダーが透明になる

この２つはTypographyプラグイン云々とは別件（たぶん私のヘッダーの実装の問題）なので、別issueにしていただけると助かります。

**Comment by Hiratake** [comment]
私の方でつくっときます

**Comment by Hiratake** [comment]
@book000 なんかそれっぽい感じに調整したので見て🙏
