### ISSUE TITLE
ハッシュ付きリンク使用時のヘッダーの動作の修正

### ISSUE THREAD

**Issue by Hiratake** [jaoafa/jaoweb4#35]
- 内部リンク部分がヘッダーに隠れる
- 内部リンクでページを開いたときにヘッダーが透明になる

https://github.com/jaoafa/jaoweb4/issues/34#issuecomment-1455986301

**Comment by book000** [comment]
## 内部リンク部分がヘッダーに隠れる

![image](https://user-images.githubusercontent.com/8929706/223070012-d2608913-ba6d-467f-abf4-afde1a64d8ed.png)

`position: fixed` の影響で、内部リンクで飛んだ際、飛んだ先がヘッダーに隠れる問題があるようです。
ググると改善策はいくつかあるようですが、どれがデファクトスタンダードなのかよくわからないので、改善策はお任せします。

## 内部リンクでページを開いたとき、ヘッダーが透明になる

![image](https://user-images.githubusercontent.com/8929706/223072222-dee0e263-9307-4ced-892a-c1a38a9699e6.png)

ページを普通に開いたあと、コンテンツ内にある内部リンクをクリックした場合は問題ないのですが、他ページから内部リンク付きリンクを踏んで遷移した場合にヘッダーが透明になるようです。再現例は [こちら](https://jaoweb.amatama.net/community/blog/example/#%E8%A6%8B%E5%87%BA%E3%81%97)。
