### ISSUE TITLE
li の中にある a タグに a タグのデフォルトデザインが適用されない

### ISSUE THREAD

**Issue by book000** [jaoafa/jaoweb4#47]
表題の通りです

![image](https://user-images.githubusercontent.com/8929706/225161354-78cddefd-d543-44a6-8845-f0f371e9076a.png)

試しに現行の `はじめての方へ` に置き換えてみたところ発生しました。
期待される動作は、画像内の「公式Discordサーバ」や「公式Twitter」といった a タグが他の a タグと同様 `#0284c7` で色付けされる動作です。

**Comment by Hiratake** [comment]
pのなかのaにスタイルあててるから、tableとかもだめかも。
ほかにもありそう。
